# Utiliser une image de base Java
FROM openjdk:17-jdk-alpine

# Copier le jar dans le conteneur
COPY target/configmaster_backend-0.0.1-SNAPSHOT.jar app.jar

# Exposer le port sur lequel Spring Boot écoute (par défaut 8080)
EXPOSE 8080

# Commande pour démarrer l’application
ENTRYPOINT ["java","-jar","/app.jar"]
