# ==========================
#  Configuration de l'application
# ==========================

spring.application.name=configmaster_backend
#spring.datasource.url=jdbc:oracle:thin:@//10.110.120.14:1521/PCARD
#spring.datasource.username=POWERTNR
#spring.datasource.password=pcard001
#spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
#spring.jpa.hibernate.ddl-auto=none
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect

#spring.jpa.show-sql=true
