# ==========================
#  Configuration de l'application
# ==========================


spring.application.name=configmaster_backend
spring.application.name=configmaster_backend
spring.datasource.url=jdbc:oracle:thin:@//10.110.120.14:1521/PCARD
spring.datasource.username=POWERCARD
spring.datasource.password=pcard001
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect
server.port=8084
spring.jpa.show-sql=true
server.servlet.context-path=/configmaster_backend

##################Unix


unix.serverbo.host=10.110.120.34
unix.serverbo.user=pwrcarbo
unix.serverbo.password=Pwc009*$*
unix.serverof.host=10.110.120.34
unix.serverof.user=pwrcarbo
unix.serverof.password=Pwc009*$*

unix.server.promptTn=pwrtnrbo:mlbappuat1:/pwrcard/pwrtnrbo/usr/
unix.server.promptSt=pwrcarbo:mlbappuat1:/pwrcard/pwrcarbo/usr/

unix.server.pathBackOffice=usr/
unix.server.pathOffline=
#unix.server.scriptPath
